spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"
        git:
          uri: "https://github.com/san1jad/config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #----config to activate rabbit mq
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#----config to activate actuator for all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: 123456789
server:
  port: 8071